apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-service
spec:
  replicas: 2 # Забезпечуємо відмовостійкість та масштабування
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: denysstarchenko/auth-service:latest
          imagePullPolicy: IfNotPresent # Обов'язково для локальних образів!
          ports:
            - containerPort: 8081
          env:
            # 1. СЕКРЕТИ (з Secrets)
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret

            # 2. КОНФІГУРАЦІЯ (з ConfigMap)
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db-host
            - name: JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: jwt-expiration

            # 3. ПРЯМЕ ПЕРЕВИЗНАЧЕННЯ URL (Spring пріоритет)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/lab4_auth_db"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP # Доступний тільки всередині кластера
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081