apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Значення: denis
  db-password: ZGVuaXM=
  # Твій довгий ключ з application.yml
  jwt-secret: NDA0RTYzNTI2NjU1Nko1WDZOMnIyNTc1Mzg3ODJmNDEzRjQ0Mjg0NzJCNEI2MjUwNjRTNjc1NjZCNTk3MA==